BoticaSanGabriel/ViewModels/Lote/LoteViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using BSG.DATACONTRACT;

namespace BoticaSanGabriel.ViewModels.Lote
{
    public class LoteViewModel
    {
        public ProductoBE Producto { get; set; }
        public List<ProductoBE> ListaProductos { get; set; }
        public LoteBE Lote { get; set; }
        public List<LoteBE> ListaLotes { get; set; }
    }
}

BoticaSanGabriel/Controllers/Lote/LoteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BSG.DATACONTRACT;
using BSG.BUSSINESS;
using BoticaSanGabriel.ViewModels.Lote;

namespace BoticaSanGabriel.Controllers.Lote
{
    public class LoteController : Controller
    {
        //
        // GET: /Lote/

        public ActionResult Index()
        {
            bool result = false;
            string mensaje = string.Empty;
            LoteViewModel model = new LoteViewModel();
            List<LoteBE> LoteList = LoteBL.Instancia.ObtenerLotes(new LoteBE(), ref result, ref mensaje);
            model.ListaLotes = LoteList;
            return View(model);
        }

        [Authorize]
        [HttpGet]
        public ActionResult Registrar(int idProducto)
        {
            bool result = false;
            string mensaje = string.Empty;
            ProductoBE Producto = new ProductoBE();
            LoteBE NuevoLote = new LoteBE();
            LoteViewModel model = new LoteViewModel();
            Producto.idProducto = idProducto;
            Producto = ProductoBL.Instancia.ObtenerProductos(Producto, ref result, ref mensaje).FirstOrDefault();
            NuevoLote.idProducto = Producto.idProducto;
            NuevoLote.nombre = Producto.nombre;
            NuevoLote.codigoProducto = Producto.codigo;
            model.Producto = Producto;
            model.Lote = NuevoLote;
            return View(model);
        }

        [HttpPost]
        public JsonResult Registrar(LoteViewModel model)
        {
            bool result = false;
            string mensaje = string.Empty;
            LoteBE LoteNuevo = new LoteBE();
            model.Lote.UsuarioMaster = Session["Usuario"].ToString();
            LoteNuevo = LoteBL.Instancia.RegistrarLote(model.Lote, ref result, ref mensaje);
            return Json(new { ok = result, data = LoteNuevo, mensaje = mensaje });
        }

        [Authorize]
        [HttpGet]
        public ActionResult Editar(int idLote)
        {
            bool result = false;
            string mensaje = string.Empty;
            LoteBE EditLote = new LoteBE();
            LoteViewModel model = new LoteViewModel();
            EditLote.idLote = idLote;
            EditLote = LoteBL.Instancia.ObtenerLotes(EditLote, ref result, ref mensaje).FirstOrDefault();
            model.Lote = EditLote;
            return View(model);
        }

        [HttpPost]
        public JsonResult Editar(LoteViewModel model)
        {
            bool result = false;
            string mensaje = string.Empty;
            LoteBE LoteEditado = new LoteBE();
            model.Lote.UsuarioMaster = Session["Usuario"].ToString();
            LoteEditado = LoteBL.Instancia.EditarLote(model.Lote, ref result, ref mensaje);
            return Json(new { ok = result, data = LoteEditado, mensaje = mensaje });
        }

        [HttpPost]
        public JsonResult Eliminar(LoteViewModel model)
        {
            bool result = false;
            string mensaje = string.Empty;
            LoteBE LoteEliminado = new LoteBE();
            model.Lote.UsuarioMaster = Session["Usuario"].ToString();
            LoteEliminado = LoteBL.Instancia.EliminarLote(model.Lote, ref result, ref mensaje);
            return Json(new { ok = result, data = LoteEliminado, mensaje = mensaje });
        }
    }
}

BoticaSanGabriel/Controllers/Producto/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BoticaSanGabriel.ViewModels.Producto;
using BSG.BUSSINESS;
using BSG.DATACONTRACT;

namespace BoticaSanGabriel.Controllers.Producto
{
    public class ProductoController : Controller
    {
        //
        // GET: /Producto/
        [Authorize]
        [HttpGet]
        public ActionResult Index()
        {
            bool result = false;
            string mensaje = string.Empty;
            ProductoViewModel model = new ProductoViewModel();
            model.ListUnidadMedida = ProductoBL.Instancia.ObtenerUnidadMedida();
            model.ListaProductos = ProductoBL.Instancia.ObtenerProductos(new ProductoBE(),ref result,ref mensaje);
            return View(model);
        }

        [Authorize]
        [HttpGet]
        public ActionResult Registrar()
        {
            ProductoViewModel model = new ProductoViewModel();
            model.ListUnidadMedida = ProductoBL.Instancia.ObtenerUnidadMedida();
            return View(model);
        }

        [HttpPost]
        public JsonResult Registrar(ProductoViewModel model)
        {
            bool result = false;
            string mensaje = string.Empty;
            ProductoBE ProductoNuevo = new ProductoBE();
            model.Producto.UsuarioMaster = Session["Usuario"].ToString();
            ProductoNuevo = ProductoBL.Instancia.RegistrarProducto(model.Producto, ref result, ref mensaje);
            return Json(new { ok = result, data = ProductoNuevo, mensaje = mensaje });
        }

        [Authorize]
        [HttpGet]
        public ActionResult Editar(int idProducto)
        {
            bool result = false;
            string mensaje = string.Empty;
            ProductoViewModel model = new ProductoViewModel();
            ProductoBE producto = new ProductoBE();
            producto.idProducto = idProducto;
            model.Producto = ProductoBL.Instancia.ObtenerProductos(producto, ref result, ref mensaje).FirstOrDefault();
            model.ListUnidadMedida = ProductoBL.Instancia.ObtenerUnidadMedida();
            return View(model);
        }

        [HttpPost]
        public JsonResult Editar(ProductoViewModel model)
        {
            bool result = false;
            string mensaje = string.Empty;
            model.Producto.UsuarioMaster = Session["Usuario"].ToString();
            ProductoBL.Instancia.EditarUsuario(model.Producto, ref result, ref mensaje);
            return Json(new { ok = result, mensaje = mensaje });
        }

        public JsonResult Eliminar(ProductoViewModel model)
        {
            bool result = false;
            string mensaje = string.Empty;
            model.Producto.UsuarioMaster = Session["Usuario"].ToString();
            ProductoBL.Instancia.EliminarProducto(model.Producto, ref result, ref mensaje);
            return Json(new { ok = result, mensaje = mensaje });
        }

    }
}

BoticaSanGabriel/Views/Lote/Lote/Editar.cshtml
@using BoticaSanGabriel.Extenciones;
@model BoticaSanGabriel.ViewModels.Lote.LoteViewModel
<div class="panel panel-default">
    <div class="panel-heading">
        <strong>Editar Lote</strong>
    </div>
    <div class="panel-body">
        <div class="col-lg-12">
            <div class="panel-body pan">
                <div class="form-body pal">
                    <form data-bind="submit: EditarLote">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label">Codigo Producto</label>
                                    <div class="input-icon right">
                                        <i class="fa fa-medkit"></i>
                                        <input id="" type="text" data-bind="value: LoteEditar().codigoProducto" class="form-control" disabled>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label">Producto</label>
                                    <div class="input-icon right">
                                        <i class="fa"></i>
                                        <input id="" type="text" data-bind="value: LoteEditar().nombre" class="form-control" disabled>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label">Codigo Lote</label>
                                    <div class="input-icon right">
                                        <i class="fa fa-hashtag"></i>
                                        <input id="" type="text" data-bind="value: LoteEditar().codigoLote" class="form-control" required>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label">Fecha Vencimiento</label>
                                    <div class="input-icon left">
                                        <i class="fa fa-calendar"></i>
                                        <input id="" type="date" data-bind="date: LoteEditar().fechaVencimiento" class="form-control" required>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label">Stock Mostrador</label>
                                    <div class="input-icon right">
                                        <i class="fa fa-inbox"></i>
                                        <input id="" type="text" data-bind="value: LoteEditar().StockMostrador" class="form-control" required>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label">Stock Almacen</label>
                                    <div class="input-icon right">
                                        <i class="fa fa-inbox"></i>
                                        <input id="" type="text" data-bind="value: LoteEditar().StockAlmacen" class="form-control" required>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="text-right pal">
                            <button type="submit" class="btn btn-primary" data-bind="enable: StockTotal() > 0">
                                Editar Lote</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/javascript">

    ko.extenders.numeric = function (target, precision) {
        var result = ko.computed({
            read: target,
            write: function (newValue) {
                var current = target(),
                    roundingMultiplier = Math.pow(10, precision),
                    newValueAsNum = isNaN(newValue) ? 0 : parseFloat(+newValue),
                    valueToWrite = Math.round(newValueAsNum * roundingMultiplier) / roundingMultiplier;
                if (valueToWrite !== current) {
                    target(valueToWrite);
                } else {
                    if (newValue !== current) {
                        target.notifySubscribers(valueToWrite);
                    }
                }
            }
        }).extend({ notify: 'always' });
        result(target());
        return result;
    };

    function LoteBE(i) {
        var self = this;
        self.idLote = ko.observable(i.idLote); self.codigoLote = ko.observable(i.codigoLote); self.idProducto = ko.observable(i.idProducto);
        self.codigoProducto = ko.observable(i.codigoProducto); self.StockMostrador = ko.observable(i.StockMostrador).extend({ numeric: 1 });
        self.StockAlmacen = ko.observable(i.StockAlmacen).extend({ numeric: 1 }); self.fechaVencimiento = ko.observable(i.fechaVencimiento);
        self.cantidad = ko.observable(i.cantidad); self.nombre = ko.observable(i.nombre);
    }

    function ViewModel(model) {
        var self = this;
        
        self.LoteEditar = ko.observable(new LoteBE(model.Lote));

        self.StockTotal = ko.computed(function () {
            return self.LoteEditar().StockAlmacen() + self.LoteEditar().StockMostrador()
        });
        
        self.EditarLote = function () {
            var data = ko.toJSON({ Lote: self.LoteEditar });
            $.ajax({
                url: '@Url.Action("Editar", "Lote")',
                dataType: "json",
                contentType: "application/json",
                type: "POST",
                data: data,
                success: function (result) {
                    if (result.ok) {
                        DivAlert('S', result.mensaje);
                    }
                    else {
                        DivAlert('D', result.mensaje);
                    }
                    self.LimpiarCampos();
                }
            });
        }

        }

        var model = new ViewModel(@Html.HtmlConvertToJson(Model));
    ko.applyBindings(model);
</script>

BoticaSanGabriel/Views/Lote/Lote/Index.cshtml
@using BoticaSanGabriel.Extenciones;
@model BoticaSanGabriel.ViewModels.Lote.LoteViewModel
<div class="panel panel-default">
    <div class="panel-heading">
        <strong>Bandeja Lotes</strong>
    </div>
    <div class="panel-body">
        <nav role="navigation" class="navbar navbar-default">
            <div class="container-fluid">
                <div class="collapse navbar-collapse">
                    <div role="search" class="navbar-form navbar-left">
                        <div class="form-group">
                            <input type="text" placeholder="Buscar" data-bind="value: Filtrar" class="form-control">
                        </div>
                        <button class="btn btn-grey">Buscar</button>
                    </div>
                    <div class="navbar-form navbar-right">
                        <button class="btn btn-grey" data-bind="click: NuevoLote">Nuevo</button>
                    </div>
                </div>
            </div>
        </nav>

        <div class="panel panel-grey">
            <div class="panel-body">
                <table class="table table-hover-color">
                    <thead>
                        <tr>
                            <th>Codigo Lote</th>
                            <th>Nombre de Producto</th>
                            <th>Stock Total</th>
                            <th>Stock Disponible</th>
                            <th>Fecha Vencimiento</th>
                            <th>Estado Lote</th>
                        </tr>
                    </thead>
                    <tbody data-bind="foreach: LotesFiltrados.currentPageData">
                        <tr data-bind="event: {dblclick: $parent.seleccionar}, attr: { class: StatusLote }">
                            <td data-bind="text: codigoLote"></td>
                            <td data-bind="text: nombre"></td>
                            <td data-bind="text: StockTotal"></td>
                            <td data-bind="text: StockDisponible"></td>
                            <td data-bind="text: moment(fechaVencimiento()).format('L')"></td>
                            <td data-bind="text: EstadoLote"></td>
                            <td><i class="fa fa-pencil-square-o" data-bind="click: $parent.EditarLote, visible: EditValid"></i></td>
                            <td><i class="fa fa-trash-o" data-bind="click: $parent.EliminarLote, visible: EditValid"></i></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row">
            <ul class="pager">
                <li><a href="#" data-bind="click: LotesFiltrados.moveFirst">← Primero</a></li>
                <li><a href="#" data-bind="click: LotesFiltrados.movePrevious">Anterior</a></li>
                <li><a href="#" data-bind="click: LotesFiltrados.moveNext">Siguiente</a></li>
                <li><a href="#" data-bind="click: LotesFiltrados.moveLast">Ultimo →</a></li>
                Pagina    
        <input class="pager" type="number" data-bind="value: LotesFiltrados.currentPage, attr: { 'max': LotesFiltrados.pageCount }" min="1">
                de <span data-bind="text: LotesFiltrados.pageCount"></span>
            </ul>
        </div>
    </div>
</div>
<script type="text/javascript">
    //#region paginacion
    ko.extenders.paging = function (target, pageSize) {
        var _pageSize = ko.observable(pageSize || 10),
            // default pageSize to 10
            _currentPage = ko.observable(1); // default current page to 1
        target.pageSize = ko.computed({
            read: _pageSize,
            write: function (newValue) {
                if (newValue > 0) {
                    _pageSize(newValue);
                }
                else {
                    _pageSize(10);
                }
            }
        });

        target.currentPage = ko.computed({
            read: _currentPage,
            write: function (newValue) {
                if (newValue > target.pageCount()) {
                    _currentPage(target.pageCount());
                }
                else if (newValue <= 0) {
                    _currentPage(1);
                }
                else {
                    _currentPage(newValue);
                }
            }
        });

        target.pageCount = ko.computed(function () {
            return Math.ceil(target().length / target.pageSize()) || 1;
        });

        target.currentPageData = ko.computed(function () {
            var pageSize = _pageSize(),
                pageIndex = _currentPage(),
                startIndex = pageSize * (pageIndex - 1),
                endIndex = pageSize * pageIndex;

            return target().slice(startIndex, endIndex);
        });

        target.moveFirst = function () {
            target.currentPage(1);
        };
        target.movePrevious = function () {
            target.currentPage(target.currentPage() - 1);
        };
        target.moveNext = function () {
            target.currentPage(target.currentPage() + 1);
        };
        target.moveLast = function () {
            target.currentPage(target.pageCount());
        };

        return target;
    };
    //#endregion
    function LoteBE(i) {
        var self = this;
        self.idLote = ko.observable(i.idLote); self.codigoLote = ko.observable(i.codigoLote); self.idProducto = ko.observable(i.idProducto);
        self.codigoProducto = ko.observable(i.codigoProducto); self.StockMostrador = ko.observable(i.StockMostrador).extend({ numeric: 1 });
        self.StockAlmacen = ko.observable(i.StockAlmacen).extend({ numeric: 1 }); self.fechaVencimiento = ko.observable(i.fechaVencimiento);
        self.cantidad = ko.observable(i.cantidad); self.nombre = ko.observable(i.nombre); self.DiferenciaDias = ko.observable(i.DiferenciaDias);
        self.StockDisponible = ko.observable(i.StockDisponible); self.StockTotal = ko.observable(i.StockTotal);
        self.EstadoLote = ko.observable(i.EstadoLote);
        self.StatusLote = ko.computed(function () {
            if (self.DiferenciaDias() <= 0 || self.StockDisponible() <= 0)
                return 'danger'; //danger
            else if (self.DiferenciaDias() <= 30)
                return 'warning'
            else
                return 'success';
            //return self.DiferenciaDias() <= 30 ? 'danger' : 'success'
        });
        self.EditValid = ko.computed(function () {
            if (self.StockTotal() == self.StockDisponible())
                return true;
            else
                return false;
        });
    }

    function Lote() {
        var self = this;
        self.idLote = ko.observable(); self.codigoLote = ko.observable(); self.idProducto = ko.observable();
        self.codigoProducto = ko.observable(); self.StockMostrador = ko.observable().extend({ numeric: 1 });
        self.StockAlmacen = ko.observable().extend({ numeric: 1 }); self.fechaVencimiento = ko.observable();
        self.cantidad = ko.observable(); self.nombre = ko.observable(); self.StockDisponible = ko.observable();
        self.StockTotal = ko.observable(); self.EstadoLote = ko.observable();
    }

    function ViewModel(model) {
        var self = this;
        self.ListaLotes = ko.observableArray(ko.utils.arrayMap(model.ListaLotes, function (i) {
            return new LoteBE(i)
        })).extend({ paging: 15 });

        self.EditarLote = function (i) {
            var url = '@Url.Action("Editar", "Lote")' + '?idLote=' + i.idLote();
            MostrarVistaDiv(url);
        }

        self.EliminarLote = function (i) {
            var data = ko.toJSON({ Lote: i });
            $.ajax({
                url: '@Url.Action("Eliminar", "Lote")',
                dataType: "json",
                contentType: "application/json",
                type: "POST",
                data: data,
                success: function (result) {
                    if (result.ok) {
                        self.ListaLotes.remove(i);
                        DivAlert('S', result.mensaje);
                    }
                    else {
                        DivAlert('D', result.mensaje);
                    }
                    self.LimpiarCampos();
                }
            });
        }

        self.NuevoLote = function () {
            DivAlert('S', 'Seleccione el Producto al que desea agregar el Lote.');
            MostrarVistaDiv('@Url.Action("Index", "Producto")');
        }

        self.Filtrar = ko.observable("");

        self.LotesFiltrados = ko.computed(function () {
            return ko.utils.arrayFilter(self.ListaLotes(), function (Lot) {
                var bool = false;
                if ((Lot.codigoLote().indexOf(self.Filtrar().toUpperCase()) !== -1 ||
                     Lot.nombre().indexOf(self.Filtrar().toUpperCase()) !== -1 ||
                     self.Filtrar() == ""))
                    bool = true;
                else {
                    bool = false;
                }
                return bool;
            });
        }).extend({ paging: 15 });
    }

    var model = new ViewModel(@Html.HtmlConvertToJson(Model));
    ko.applyBindings(model);
</script>

BoticaSanGabriel/Views/Lote/Lote/Registrar.cshtml
@using BoticaSanGabriel.Extenciones;
@model BoticaSanGabriel.ViewModels.Lote.LoteViewModel
<div class="panel panel-default">
    <div class="panel-heading">
        <strong>Registro Lote</strong>
    </div>
    <div class="panel-body">
        <div class="col-lg-12">
            <div class="panel-body pan">
                <div class="form-body pal">
                    <form data-bind="submit: RegistrarLote">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label">Codigo Producto</label>
                                    <div class="input-icon right">
                                        <i class="fa fa-medkit"></i>
                                        <input id="" type="text" data-bind="value: NuevoLote().codigoProducto" class="form-control" disabled>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label">Producto</label>
                                    <div class="input-icon right">
                                        <i class="fa"></i>
                                        <input id="" type="text" data-bind="value: NuevoLote().nombre" class="form-control" disabled>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label">Codigo Lote</label>
                                    <div class="input-icon right">
                                        <i class="fa fa-hashtag"></i>
                                        <input id="" type="text" data-bind="value: NuevoLote().codigoLote" class="form-control" required>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label">Fecha Vencimiento</label>
                                    <div class="input-icon left">
                                        <i class="fa fa-calendar"></i>
                                        <input id="" type="date" data-bind="value: NuevoLote().fechaVencimiento" class="form-control" required>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label">Stock Mostrador</label>
                                    <div class="input-icon right">
                                        <i class="fa fa-inbox"></i>
                                        <input id="" type="text" data-bind="value: NuevoLote().StockMostrador" class="form-control" required>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label">Stock Almacen</label>
                                    <div class="input-icon right">
                                        <i class="fa fa-inbox"></i>
                                        <input id="" type="text" data-bind="value: NuevoLote().StockAlmacen" class="form-control" required>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="text-right pal">
                            <button type="submit" class="btn btn-primary" data-bind="enable: StockTotal() > 0">
                                Crear Lote</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/javascript">

    ko.extenders.numeric = function (target, precision) {
        var result = ko.computed({
            read: target,
            write: function (newValue) {
                var current = target(),
                    roundingMultiplier = Math.pow(10, precision),
                    newValueAsNum = isNaN(newValue) ? 0 : parseFloat(+newValue),
                    valueToWrite = Math.round(newValueAsNum * roundingMultiplier) / roundingMultiplier;
                if (valueToWrite !== current) {
                    target(valueToWrite);
                } else {
                    if (newValue !== current) {
                        target.notifySubscribers(valueToWrite);
                    }
                }
            }
        }).extend({ notify: 'always' });
        result(target());
        return result;
    };

    function LoteBE(i) {
        var self = this;
        self.idLote = ko.observable(i.idLote); self.codigoLote = ko.observable(i.codigoLote); self.idProducto = ko.observable(i.idProducto);
        self.codigoProducto = ko.observable(i.codigoProducto); self.StockMostrador = ko.observable(i.StockMostrador).extend({ numeric: 1 });
        self.StockAlmacen = ko.observable(i.StockAlmacen).extend({ numeric: 1 }); self.fechaVencimiento = ko.observable(i.fechaVencimiento);
        self.cantidad = ko.observable(i.cantidad); self.nombre = ko.observable(i.nombre);
    }

    function ViewModel(model) {
        var self = this;
        
        self.NuevoLote = ko.observable(new LoteBE(model.Lote));
        self.StockTotal = ko.computed(function () {
            return self.NuevoLote().StockAlmacen() + self.NuevoLote().StockMostrador()
        });
        
        self.RegistrarLote = function () {
            var data = ko.toJSON({ Lote: self.NuevoLote });
            $.ajax({
                url: '@Url.Action("Registrar", "Lote")',
                dataType: "json",
                contentType: "application/json",
                type: "POST",
                data: data,
                success: function (result) {
                    if (result.ok) {
                        DivAlert('S', result.mensaje);
                        var url = '@Url.Action("Editar", "Lote")' + '?idLote=' + result.data.idLote;
                        MostrarVistaDiv(url);
                    }
                    else {
                        DivAlert('D', result.mensaje);
                    }
                    self.LimpiarCampos();
                }
            });
        }

        }

        var model = new ViewModel(@Html.HtmlConvertToJson(Model));
    ko.applyBindings(model);
</script>