BoticaSanGabriel/ViewModels/Util/InicioViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using BSG.DATACONTRACT;

namespace BoticaSanGabriel.ViewModels.Util
{
    public class InicioViewModel
    {
        public List<ModuloBE> ListaModulos { get; set; }
        public ModuloBE ModuloActual { get; set; }

    }
}

BoticaSanGabriel/Controllers/Prueba/PruebaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BoticaSanGabriel.ViewModels.Prueba;

namespace BoticaSanGabriel.Controllers.Prueba
{
    public class PruebaController : Controller
    {
        //
        // GET: /Prueba/

        public ActionResult Index()
        {
            PruebaViewModel model = new PruebaViewModel();

            model.nombre = "Ronald";
            model.apellido = "Pacheco Alarcón";
            model.ListaPaises = new List<Paises>();
            Paises Pais1 = new Paises();
            Pais1.idPais = 1;
            Pais1.Pais = "Perú";
            Pais1.Continente = "America";
            model.ListaPaises.Add(Pais1);

            Paises Pais2 = new Paises();
            Pais2.idPais = 2;
            Pais2.Pais = "Francia";
            Pais2.Continente = "Europa";
            model.ListaPaises.Add(Pais2);

            //var initialData = [
            //                    {
            //                        firstName: "Danny", lastName: "LaRusso", phones: [
            //                          { type: "Mobile", number: "(555) 121-2121" },
            //                          { type: "Home", number: "(555) 123-4567" }]
            //                    },
            //                    {
            //                        firstName: "Sensei", lastName: "Miyagi", phones: [
            //                          { type: "Mobile", number: "(555) 444-2222" },
            //                          { type: "Home", number: "(555) 999-1212" }]
            //                    }
            //                    ];

            //model.contacto = new List<contacto>();

            //contacto contacto1 = new contacto();
            //contacto1.firstName = "Ronald";
            //contacto1.lastName = "Pacheco Alarcón";
            //contacto1.phones = new List<phone>();
            //phone phone11 = new phone();
            //phone11.type = "MOBIL";
            //phone11.number = "0939393933";
            //contacto1.phones.Add(phone11);
            //model.contacto.Add(contacto1);

            //contacto contacto12 = new contacto();
            //contacto12.firstName = "Soledad";
            //contacto12.lastName = "Nuñez de La Cruz";
            //contacto12.phones = new List<phone>();
            //phone phone12 = new phone();
            //phone12.type = "Casa";
            //phone12.number = "96323193892";
            //contacto12.phones.Add(phone12);
            //model.contacto.Add(contacto12);

            return View(model);
        }
    }
}

BoticaSanGabriel/Views/Shared/Inicio.cshtml
@model BoticaSanGabriel.ViewModels.Util.InicioViewModel

<script type="text/javascript">
    function MostrarVistaDiv(url) {
        var idDiv = 'page-wrapper';
        $.ajax({
            type: 'GET',
            url: url,
            cache: false,
            success: function (data, textStatus, xhr) {
                $('#' + idDiv).html(data);
            },
            error: function (xhr, ajaxOptions, thrownError) {
                alert('Error: ' + xhr.status + ' - ' + thrownError);
            }
        });
    }

    function ActiveModulo(id) {
        $('#side-menu li').each(function (index) {
            $(this).removeClass();
        });
        $('#' + id).addClass('active');
    }
</script>

<!DOCTYPE html>
<html lang="es">

<head>
    <title>Pagina Principal</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="images/icons/favicon.ico">
    <link rel="apple-touch-icon" href="images/icons/favicon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="images/icons/favicon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="images/icons/favicon-114x114.png">
    <link type="text/css" rel="stylesheet" href="../Content/styles/jquery-ui-1.10.4.custom.min.css">
    @*<link type="text/css" rel="stylesheet" href="../Content/styles/font-awesome.min.css">
    <link type="text/css" rel="stylesheet" href="../Content/styles/font-awesome.css">*@
    <link type="text/css" rel="stylesheet" href="../Content/font-awesome-4.5.0/css/font-awesome.min.css">
    <link type="text/css" rel="stylesheet" href="../Content/font-awesome-4.5.0/css/font-awesome.css">
    <link type="text/css" rel="stylesheet" href="../Content/styles/bootstrap.min.css">
    <link type="text/css" rel="stylesheet" href="../Content/styles/animate.css">
    <link type="text/css" rel="stylesheet" href="../Content/styles/all.css">
    <link type="text/css" rel="stylesheet" href="../Content/styles/main.css">
    <link type="text/css" rel="stylesheet" href="../Content/styles/style-responsive.css">
    <link type="text/css" rel="stylesheet" href="../Content/styles/zabuto_calendar.min.css">
    <link type="text/css" rel="stylesheet" href="../Content/styles/pace.css">
    <link type="text/css" rel="stylesheet" href="../Content/styles/jquery.news-ticker.css">
    <script src="~/Scripts/knockout-2.1.0.js" type="text/javascript"></script>
    <script src="~/Scripts/ko.editables.js" type="text/javascript"></script>
    <script src="~/Scripts/knockout-mapping.js" type="text/javascript"></script>
    <script src="~/Scripts/moment.js" type="text/javascript"></script> 
    <script src="~/Scripts/knockout-date-bindings.js" type="text/javascript"></script>
</head>

<body>

    <div>
        <!--BEGIN THEME SETTING-->
        <!--END THEME SETTING-->
        <!--BEGIN BACK TO TOP-->
        <a id="totop" href="#"><i class="fa fa-angle-up"></i></a>
        <!--END BACK TO TOP-->
        <!--BEGIN TOPBAR-->
        <div id="header-topbar-option-demo" class="page-header-topbar">
            <nav id="topbar" role="navigation" style="margin-bottom: 0;" data-step="3" class="navbar navbar-default navbar-static-top">
                <div class="navbar-header">
                    <button type="button" data-toggle="collapse" data-target=".sidebar-collapse" class="navbar-toggle"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
                    <a id="logo" href="index.html" class="navbar-brand"><span class="fa fa-rocket"></span><span class="logo-text">RPA</span><span style="display: none" class="logo-text-icon">µ</span></a>
                </div>
                <div class="topbar-main">
                    <a id="menu-toggle" href="#" class="hidden-xs"><i class="fa fa-bars"></i></a>
                    <div class="news-update-box hidden-xs">
                        <span class="text-uppercase mrm pull-left text-white">Alertas:</span>
                        <ul id="news-update" class="ticker list-unstyled">
                            <li>PRUEBA</li>
                            <li>ALERTAS!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!</li>
                        </ul>
                    </div>
                    <ul class="nav navbar navbar-top-links navbar-right mbn">

                        <li class="dropdown topbar-user"><a data-hover="dropdown" href="#" class="dropdown-toggle">
                            <i class="fa fa-user"></i>&nbsp;<span class="hidden-xs">@Session["usuario"].ToString()</span>&nbsp;<span class="caret"></span></a>
                            <ul class="dropdown-menu dropdown-user pull-right">
                                <li><a href="Login.html"><i class="fa fa-key"></i>Log Out</a></li>
                            </ul>
                        </li>

                    </ul>
                </div>
            </nav>
        </div>
        <!--END TOPBAR-->
        <div id="wrapper">
            <!--BEGIN SIDEBAR MENU-->
            <nav id="sidebar" role="navigation" data-step="2" data-intro="Template has &lt;b&gt;many navigation styles&lt;/b&gt;"
                data-position="right" class="navbar-default navbar-static-side">
                <div class="sidebar-collapse menu-scroll">
                    <ul id="side-menu" class="nav">
                        <div class="clearfix"></div>
                        @foreach (var modulo in Model.ListaModulos)
                        {
                            <li id="@modulo.nombre"><a href="#" onclick="MostrarVistaDiv('@modulo.URL'),ActiveModulo('@modulo.nombre')"><i class="@modulo.icono">
                                <div class="icon-bg bg-orange"></div>
                            </i><span class="menu-title">@modulo.nombre</span></a></li>
                        }
                    </ul>
                </div>
            </nav>
            <!--END SIDEBAR MENU-->
            <!--BEGIN CHAT FORM-->
            <div id="page-wrapper">
                @{Html.RenderAction("Index", "Prueba");}
            </div>
            <!--END PAGE WRAPPER-->
        </div>

        <!--BEGIN MODAL CONFIG PORTLET-->
        <div id="modal-Alert" class="modal fade">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" data-dismiss="modal" aria-hidden="true" class="close">
                            &times;</button>
                        <h4 class="modal-title">Alerta</h4>
                    </div>
                    <div class="modal-body">
                        <div id="divAlert" class="alert">
                            <i id="Icon" class="fa fa"></i>
                            <strong id="Msg"></strong>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" data-dismiss="modal" class="btn btn-default">
                            Close</button>
                    </div>
                </div>
            </div>
        </div>
        <!--END MODAL CONFIG PORTLET-->
    </div>

    <script src="../Content/script/jquery-1.10.2.min.js"></script>
    <script src="../Content/script/jquery-migrate-1.2.1.min.js"></script>
    <script src="../Content/script/jquery-ui.js"></script>
    <script src="../Content/script/bootstrap.min.js"></script>
    <script src="../Content/script/bootstrap-hover-dropdown.js"></script>
    <script src="../Content/script/html5shiv.js"></script>
    <script src="../Content/script/respond.min.js"></script>
    <script src="../Content/script/jquery.metisMenu.js"></script>
    <script src="../Content/script/jquery.slimscroll.js"></script>
    <script src="../Content/script/jquery.cookie.js"></script>
    <script src="../Content/script/icheck.min.js"></script>
    <script src="../Content/script/custom.min.js"></script>
    <script src="../Content/script/jquery.news-ticker.js"></script>
    <script src="../Content/script/jquery.menu.js"></script>
    <script src="../Content/script/pace.min.js"></script>
    <script src="../Content/script/holder.js"></script>
    <script src="../Content/script/responsive-tabs.js"></script>
    <script src="../Content/script/jquery.flot.js"></script>
    <script src="../Content/script/jquery.flot.categories.js"></script>
    <script src="../Content/script/jquery.flot.pie.js"></script>
    <script src="../Content/script/jquery.flot.tooltip.js"></script>
    <script src="../Content/script/jquery.flot.resize.js"></script>
    <script src="../Content/script/jquery.flot.fillbetween.js"></script>
    <script src="../Content/script/jquery.flot.stack.js"></script>
    <script src="../Content/script/jquery.flot.spline.js"></script>
    <script src="../Content/script/zabuto_calendar.min.js"></script>
    <!--LOADING SCRIPTS FOR CHARTS-->
  @*  <script src="../Content/script/highcharts.js"></script>
    <script src="../Content/script/data.js"></script>
    <script src="../Content/script/drilldown.js"></script>
    <script src="../Content/script/exporting.js"></script>
    <script src="../Content/script/highcharts-more.js"></script>
    <script src="../Content/script/charts-highchart-pie.js"></script>
    <script src="../Content/script/charts-highchart-more.js"></script>*@


    <!--CORE JAVASCRIPT-->
    <script src="../Content/script/main.js"></script>

    <script type="text/javascript">
        function DivAlert(caso, Msg) {
            var alertClass = "";
            var IconClass = "";
            switch (caso) {
                case "D":
                    alertClass = "alert alert-danger";
                    IconClass = "fa fa-times-circle-o";
                    break;
                case "W":
                    alertClass = "alert alert-warning";
                    IconClass = "fa fa-exclamation-triangle";
                    break;
                case "S":
                    alertClass = "alert alert-success";
                    IconClass = "fa fa-check-circle-o";
                    break;
            }
            var lastAlert = $('#divAlert').attr("class");
            var lastIcon = $('#Icon').attr("class");
            $('#Icon').removeClass(lastIcon);
            $('#Icon').addClass(IconClass);
            $('#divAlert').removeClass(lastAlert);
            $('#divAlert').addClass(alertClass);
            $('#Msg').html(Msg);
            $("#modal-Alert").modal();
        }
    </script>
</body>

</html>

BoticaSanGabriel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
    <head>
        <title>@ViewBag.Title</title>
        <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
        <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>
    </head>
    <body>
            @RenderBody()
    </body>
</html>